### ISSUE TITLE
New additional classes not training

### ISSUE THREAD

**Issue by CowbungaMk1** [VainF/DeepLabV3Plus-Pytorch#122]
Hello, I am working on a project that facilitates adding new classes to the cityscapes dataset and adding these classes to dataset/cityscapes.py. However, the training doesn't seem to ever learn these classes and the IOU is always 'nan' for 19-22 (the added classes). If i switch the class ids, such as my new class 22 to 0 (in place of road) it will train that class just fine but not for the other class. Is there some weight initialization step I'm missing? thanks

**Comment by VainF** [comment]
Hello @CowbungaMk1, please modify [this line](https://github.com/VainF/DeepLabV3Plus-Pytorch/blob/4e1087de98bc49d55b9239ae92810ef7368660db/main.py#L216) to add new classes.

**Comment by CowbungaMk1** [comment]
Thanks for your quick response. I have already tried that and it still trains the original classes just fine. However the additional classes always return a MIOU of 'nan' to visdom and don't appear when using predict.

Thanks

**Comment by CowbungaMk1** [comment]
issues resolved

**Comment by JGGGBang** [comment]
> issues resolved  已解决的问题
hi,
How did you solve it
