### ISSUE TITLE
Question about train

### ISSUE THREAD

**Issue by lph529372693** [VainF/DeepLabV3Plus-Pytorch#13]
Hi

Thanks for your repo! I successfully trained the DeeplabV3Plus-Mobilenetv2 model on the Pascal2012 dataset, but my mIOU is only 69.41%(_python3 main.py --model deeplabv3plus_mobilenet --separable_conv --gpu_id 0 --year 2012_aug --crop_val --lr 0.007 --crop_size 513 --batch_size 10 --output_stride 16_).How can I improve?
Another question, why is the experimental section of mobilenetv2's paper up to 75.70% mIOU?Was it because his model had been pretrained on COCO?I'm so confused...

Look forward to your answers!

**Comment by VainF** [comment]
Hi @lph529372693 , 

> How can I improve?

Increasing the batch size may be good choice to improve its performance (batch_size=16 or larger). 

> Another question, why is the experimental section of mobilenetv2's paper up to 75.70% mIOU?Was it because his model had been pretrained on COCO?I'm so confused...

Yes, they use coco pretraining which is better than Imagenet pretraining for segmentation.

**Comment by lph529372693** [comment]
Thank you for your reply. I'm enlightened！
