### ISSUE TITLE
Only support single GPU?

### ISSUE THREAD

**Issue by Flames60** [VainF/DeepLabV3Plus-Pytorch#2]
I find that there is no 'Parallel' or 'parallel' in the codes, so I think it only supports single GPU, right?
Then how can you put 16 images on one GPU when trained on CityScapes……

Thanks for your effort!

**Comment by VainF** [comment]
Hi @Flames60, the deeplabv3-mobilenet model was trained on a single Quadro P6000 with 24G memory.  I‘m also considering adding support for DataParallel.

**Comment by VainF** [comment]
DataParallel is supported now. Please run main.py with '--gpu_id 0,1,2,3'.

**Comment by Flames60** [comment]
> DataParallel is supported now. Please run main.py with '--gpu_id 0,1,2,3'.

Thanks again~

**Comment by WangYQ999** [comment]
> DataParallel is supported now. Please run main.py with '--gpu_id 0,1,2,3'.

I set up using two GPUs, but the program only used one.  '--gpu_id 0,1'
