### ISSUE TITLE
Cityscapes test set error

### ISSUE THREAD

**Issue by xiuhui** [VainF/DeepLabV3Plus-Pytorch#24]
hi @VainF ,thanks for your share,have you ever try the cityscapes test set?I use DeepLabV3-MobileNet,but i meet some errors as flow,can you give me some advice?
the changed code is just set split='test'
...
/DeepLabV3Plus-Pytorch-master/metrics/stream_metrics.py:65: RuntimeWarning: invalid value encountered in double_scalars
  acc = np.diag(hist).sum() / hist.sum()
/DeepLabV3Plus-Pytorch-master/metrics/stream_metrics.py:66: RuntimeWarning: invalid value encountered in true_divide
  acc_cls = np.diag(hist) / hist.sum(axis=1)
/DeepLabV3Plus-Pytorch-master/metrics/stream_metrics.py:67: RuntimeWarning: Mean of empty slice
  acc_cls = np.nanmean(acc_cls)
/DeepLabV3Plus-Pytorch-master/metrics/stream_metrics.py:68: RuntimeWarning: invalid value encountered in true_divide
  iu = np.diag(hist) / (hist.sum(axis=1) + hist.sum(axis=0) - np.diag(hist))
/DeepLabV3Plus-Pytorch-master/metrics/stream_metrics.py:69: RuntimeWarning: Mean of empty slice
  mean_iu = np.nanmean(iu)
/DeepLabV3Plus-Pytorch-master/metrics/stream_metrics.py:70: RuntimeWarning: invalid value encountered in true_divide
  freq = hist.sum(axis=1) / hist.sum()
/DeepLabV3Plus-Pytorch-master/metrics/stream_metrics.py:71: RuntimeWarning: invalid value encountered in greater
  fwavacc = (freq[freq > 0] * iu[freq > 0]).sum()

Overall Acc: nan
Mean Acc: nan
FreqW Acc: 0.000000
Mean IoU: nan

**Comment by VainF** [comment]
Hi @xiuhui, there is no ground truth in the test set of cityscapes, so it fails to report validation results.

**Comment by xiuhui** [comment]
Thank you for reminding. I forgot to do the test on the website.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Gongfan Fang"<notifications@github.com&gt;; 
发送时间: 2020年9月28日(星期一) 上午9:51
收件人: "VainF/DeepLabV3Plus-Pytorch"<DeepLabV3Plus-Pytorch@noreply.github.com&gt;; 
抄送: "xh"<783379078@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [VainF/DeepLabV3Plus-Pytorch] Cityscapes test set error (#24)





 
Hi @xiuhui, there is no ground truth in the test set of cityscapes, so it fails to report validation results.
