### ISSUE TITLE
Deeplab code not implemented

### ISSUE THREAD

**Issue by shrutishrestha** [VainF/DeepLabV3Plus-Pytorch#25]
Why everything comes to this line calling DeepLabV3 but it is not implemented as shown in the figure below?

    if name=='deeplabv3plus':
        return_layers = {'high_level_features': 'out', 'low_level_features': 'low_level'}
        classifier = DeepLabHeadV3Plus(inplanes, low_level_planes, num_classes, aspp_dilate)
    elif name=='deeplabv3':
        return_layers = {'high_level_features': 'out'}
        classifier = DeepLabHead(inplanes , num_classes, aspp_dilate)
    backbone = IntermediateLayerGetter(backbone, return_layers=return_layers)

    model = DeepLabV3(backbone, classifier)
    return model

<img width="715" alt="deeplab" src="https://user-images.githubusercontent.com/33342277/95440736-fd941d00-0978-11eb-920f-7980f388aced.png">

**Comment by VainF** [comment]
Hi @shrutishrestha , DeeplabV3 is a subclass of [_SimpleSegmentationModel](https://github.com/VainF/DeepLabV3Plus-Pytorch/blob/master/network/utils.py#L7).

**Comment by VainF** [comment]
Hi @shrutishrestha, DeepLabV3 inherits the implementation of [_SimpleSegmentationModel](https://github.com/VainF/DeepLabV3Plus-Pytorch/blob/master/network/utils.py#L7)
