### ISSUE TITLE
HRNet pretrained model

### ISSUE THREAD

**Issue by B-1368** [VainF/DeepLabV3Plus-Pytorch#64]
Hi, thanks for your recent update for HRNet support. It seems pretrained HRNet models is needed  for DeepLabV3+, but I cannot them in the link  you provided. Are you planning to upload these pretrained HRNet models? Thanks.

**Comment by VainF** [comment]
Hi @B-1368, the HRNet support was contributed by @timothylimyl. A download link is available at https://github.com/VainF/DeepLabV3Plus-Pytorch/blob/4165f1ab36af8bb5cb7dfdd21c4eec3b7d202187/network/backbone/hrnetv2.py#L9. 

We will add more information about hrnet in the readme and upload more resources in the next version.

**Comment by B-1368** [comment]
Thanks a lot!

**Comment by Uesr-NO-1** [comment]
Hello, I looked according to the instructions, but it seems the pre-trained weights for HRNet have expired again. Could you provide them again? Thank you very much!
