### ISSUE TITLE
Prediction script only loads PNGs from a file, ignores JPG

### ISSUE THREAD

**Issue by jeremywrnr** [VainF/DeepLabV3Plus-Pytorch#67]
https://github.com/VainF/DeepLabV3Plus-Pytorch/blob/3f84cd27d5e845c9d92aed6639b0685ef22ed964/predict.py#L78

Right now the prediction script ignores JPG inputs. Changing this line to something like:

```python
files = glob(os.path.join(opts.input, '**/*.' + ext), recursive=True)
```

fixes this, though.

**Comment by VainF** [comment]
Thanks!
