### ISSUE TITLE
The result of the testing code

### ISSUE THREAD

**Issue by bobthepoet** [VainF/DeepLabV3Plus-Pytorch#77]
Hi, I used the test code with your pretrained model, but the result seems to be a chaos. could you please tell me the the reason? Thanks a lot
![bremen_000000_000019_leftImg8bit](https://user-images.githubusercontent.com/95471632/164414644-f2a08534-3729-4a87-9d90-b52e70410a21.png)

**Comment by farazBhatti** [comment]
I am having same issue

**Comment by lcr9875** [comment]
@VainF  this is my code and results:
python predict.py 
--input samples/1_image.png  
--dataset cityscapes 
--model deeplabv3plus_mobilenet 
--ckpt checkpoints/best_deeplabv3plus_mobilenet_cityscapes_os16.pth
--save_val_results_to test_results 
![image](https://user-images.githubusercontent.com/51826346/179730574-989f2bdc-ba47-4dc5-bb77-e22406345ec2.png)

**Comment by lcr9875** [comment]
> 

oh,I know the reason,because the dataset is not suitable,I use voc just ok.

**Comment by gaoxumustwin** [comment]
@lcr9875 Hello brother, I see that you and I are inferring an image, but my VOC type inference is still inaccurate. The command is as follows:
python predict.py --input test/1_image.png  --dataset voc --model deeplabv3plus_mobilenet --ckpt checkpoints/best_deeplabv3_mobilenet_voc_os16.pth --save_val_results_to test_results
![Uploading 1_image.png…]()

**Comment by gaoxumustwin** [comment]
@lcr9875  Hello brother, I see that you and I are inferring an image, but my VOC type inference is still inaccurate. The command is as follows:
python predict.py --input test/1_image.png --dataset voc --model deeplabv3plus_mobilenet --ckpt checkpoints/best_deeplabv3_mobilenet_voc_os16.pth --save_val_results_to test_results
![1_image](https://github.com/user-attachments/assets/bcdf6071-ed27-4eda-86a4-d8db0bff0d7a)
