### ISSUE TITLE
train my own dataset 

### ISSUE THREAD

**Issue by Young8768** [VainF/DeepLabV3Plus-Pytorch#80]
@VainF Hi ,thans for your great work。
Recently I met some problems when I study your work. I want to train my own dataset by deeplabv3plus，so I transform my data formats to  VOC2012, and change the prams(number cls = 4 (3 + background)/batch-size, et).Then I train my model, error report as follow image.
![image](https://user-images.githubusercontent.com/37794785/170944257-72e5ede3-7e27-4bca-871b-9663f8c3608e.png)

hope your reply，thanks.

**Comment by Young8768** [comment]
@VainF Thanks for your reply，and I  will check them. 
 I am sure the num_classes is correct，3（real targets）+1（background）.But I dont know how to set ignore_index(default is 255).

**Comment by tuanndhust** [comment]
@Young8768  Can you tell me how to set ignore_index ? Thank you very much.

**Comment by IremYoldas** [comment]
Hi @Young8768, did you change colormap (cmap) in voc.py? Thanks in advance.
